#!/bin/sh

# This will:
# 1) check to see if it is cached already.
# 2)   if not, figure out the right verion to pull

set -e
IMG=${1}
REPO=$(echo $IMG|sed 's/@.*//') 
HASH=$(echo $IMG|sed 's/.*@//') 
ID=$(echo $IMG|sed 's/.*://')

# Try running it...
set +e
shifter --image=id:${ID} echo yes > /dev/null 2>&1 && echo ${ID} && exit
set -e

#Try to figure out the version to pull
RT=$(skopeo inspect docker://${IMG}|jq .RepoTags)
for ttag in $(echo $RT|sed 's/[",[]//g') ; do
	digest=$(skopeo inspect docker://${REPO}:${ttag}|jq .Digest|sed 's/"//g') 
	if [ "$digest" == "$HASH" ] ; then
		TAG=$ttag
		break
	fi
done
if [ -z $TAG ] ; then
	echo "Unable to determine image version" 1>&2
	exit 1
fi

# Pull image by tag
shifterimg pull ${REPO}:${TAG} 1>&2

# Get the ID
id=$(shifterimg lookup ${REPO}:${TAG})

echo "${IMG} ${id}" 1>&2
echo "${id}"
